CHARACTER_X                 EQU 3
CHARACTER_ACTION            EQU 0
CHARACTER_ACTION_TABLE      EQU 1  ;DW
CHARACTER_Y                 EQU 4
CHARACTER_TYPE              EQU 5
CHARACTER_ANIMATION         EQU 6
CHARACTER_FRAME             EQU 7
CHARACTER_DATA              EQU 8
CHARACTER_SIZE              EQU 32